const constants = {
    LOGGED_IN_TOKEN: 'LOGGED_IN_TOKEN',
    GUEST_USER_TOKEN: 'GUEST_USER_TOKEN',
    PICK_UP_ADDRESS: 'PICK_UP_ADDRESS',
    NEAREST_STORE:'NEAREST_STORE',
    NEAREST_CODE:'NEAREST_PINCODE',
    TRACK_ID:'TRACKING_ID',
    MAIL:"ecommerce@hap.in",
    TOAST_DURATION: 3000,
    TEST_TELYPORT_API_KEY: '6DHA5AI95J2WCN0FRA096OEALCJKKH',
    PRODUCTION_TELYPORT_API_KEY: 'X2D9BGNUDQN7D7U89NPVOV0M1ANA4Z',
    TEST_RAZORPAY_API_KEY: 'rzp_test_fEzXYCb7uBVqKP',
    GOOGLE_PLACES_API_KEY: 'AIzaSyDJGvWWnPMZ9JMfUHQT3dIAcIw54LxM0Vc',
    PRODUCTION_RAZORPAY_API_KEY: 'rzp_live_Vz8uIp1N7EfRBF',
}

export default constants