const ImageAssets = {
  // Common-images
  iconhap: require('./icons/common_icons/ic_launcher.png'),
  iconmap:require('./icons/common_icons/hap-daily-map-pointer-3.png'),
  sqiconhap: require('./icons/common_icons/sq_launcher.png'),
  delivered:require('./icons/order_delivered.png'),
  ibacologo: require('./icons/common_icons/Ibaco_Transparent_logo.png'),
  ibacologowithbg: require('./icons/common_icons/Ibaco_logo.jpg'),
  shopping_cart:require('./icons/shopping-cart.png'),
  search: require('./icons/common_icons/search.png'),
  close: require('./icons/close/close.png'),
  remove: require('./icons/close/remove.png'),
  group: require('./icons/common_icons/group.png'),
  chopServe: require('./icons/common_icons/chopserve.png'),
  cross: require('./icons/common_icons/cross.png'),
  refresh:require('./icons/refresh.png'),
  order_delivered_page_chef:require('./icons/cowimg.png'),
  home_dark: require('./icons/common_icons/home_dark.png'),
  others: require('./icons/common_icons/others.png'),
  work_dark: require('./icons/common_icons/work_dark.png'),
  new_address: require('./icons/common_icons/new_address.png'),
  arrow_forward: require('./icons/common_icons/arrow_forward.png'),
  home_white: require('./icons/common_icons/home_white.png'),
  favourites_icon_active: require('./icons/common_icons/favourites_icon_active.png'),
  favourites_icon_inactive: require('./icons/common_icons/favourites_icon_inactive.png'),
  radio_active_icon: require('./icons/common_icons/radio_active_icon.png'),
  radio_inactive_icon: require('./icons/common_icons/radio_inactive_icon.png'),
  radio_square_button_inactive: require('./icons/common_icons/radio_square_button_inactive.png'),
  radio_square_button_active: require('./icons/common_icons/radio_square_button_active.png'),
  work_white: require('./icons/common_icons/work_white.png'),
  others_white: require('./icons/common_icons/others_white.png'),
  arrow_backword: require('./icons/common_icons/arrow_backword.png'),
  pincode_dropdown: require('./icons/common_icons/pincode_dropdown.png'),
  ibaco_carousel: require('./icons/common_icons/ibaco_carousel.jpg'),
  ibaco_carousel2: require('./icons/common_icons/ibaco_carousel_2.jpg'),

  egg_active: require('./icons/tab_inactive.svg'),
  red_arrow_icon_common: require('./icons/common_icons/red_arrow_icon_common.png'),
  banner: require('./icons/common_icons/ibaco_carousel.jpg'),

  // Account
  account_bottom_tab_inactive: require('./icons/account/account_bottom_tab_inactive.png'),
  account_bottom_tab_active: require('./icons/account/account_bottom_tab_active.png'),
  order_active: require('./icons/account/order_active.png'),
  order_inactive: require('./icons/account/order_inactive.png'),
  profile: require('./icons/account/profile.png'),
  profile_active: require('./icons/account/profile_active.png'),
  referral_active: require('./icons/account/referral_active.png'),
  referral_inactive: require('./icons/account/referral_inactive.png'),
  wallet_active: require('./icons/account/wallet_active.png'),
  wallet_inactive: require('./icons/account/wallet_inactive.png'),
  referral_people_image: require('./icons/account/referral_people_image.png'),
  calender_icon: require('./icons/account/calender_icon.png'),
  account_header_active: require('./icons/account/account_header_active.png'),
  profile_inactive: require('./icons/account/profile_inactive.png'),
  accounticon: require('./icons/account/accounticon.png'),

  // Blog
  blog_bottom_tab_inactive: require('./icons/blog/blog_bottom_tab_inactive.png'),
  blog_bottom_tab_active: require('./icons/blog/blog_bottom_tab_active.png'),
  blog_category_scroll: require('./icons/blog/blog_category_scroll.png'),
  blog_header_active: require('./icons/blog/blog_header_active.png'),
  blog_ledy: require('./icons/blog/blog_ledy.png'),

  // Cart
  cart_bottom_tab_inactive: require('./icons/cart/cart_bottom_tab_inactive.png'),
  cart_bottom_tab_active: require('./icons/cart/cart_bottom_tab_active.png'),
  cart_header: require('./icons/cart/cart_header.png'),
  cart: require('./icons/cart/cart.png'),
  cross_small: require('./icons/cart/cross_small.png'),
  empty_cart: require('./icons/cart/empty_cart.png'),
  go_grab: require('./icons/cart/go_grab.png'),
  cart_product_red_square_icon: require('./icons/cart/cart_product_red_square_icon.png'),

  // Order
  box: require('./icons/order/box.png'),
  hurry: require('./icons/order/hurry.png'),
  order_bottom_tab_inactive: require('./icons/order/order_bottom_tab_inactive.png'),
  order_bottom_tab_active: require('./icons/order/order_bottom_tab_active.png'),
  bill_details_arrow: require('./icons/order/bill_details_arrow.png'),
  order_tracking_motorman: require('./icons/order/order_tracking_motorman.png'),
  order_tracking_colaps_icon: require('./icons/order/order_tracking_colaps_icon.png'),
  order_tracking_phone_icon: require('./icons/order/order_tracking_phone_icon.png'),
  order_tracking_radiobutton_complete: require('./icons/order/order_tracking_radiobutton_complete.png'),
  order_tracking_radiobutton_itemOnWay: require('./icons/order/order_tracking_radiobutton_itemOnWay.png'),
  help_email_icon: require('./icons/order/help_email_icon.png'),
  Order_cancelled: require('./icons/order/Order_cancelled.png'),
  help_question_icon: require('./icons/order/help_question_icon.png'),
  check_icon: require('./icons/order/check.png'),
  no_order: require('./icons/order/no_order.png'),
  orderHistory_arrow: require('./icons/order/orderHistory_arrow.png'),

  // Shop
  pincode_location: require('./icons/shop/location.png'),
  scroll_arrow: require('./icons/shop/scroll_arrow.png'),
  shop_header: require('./icons/shop/shop_head.jpg'),
  store_img: require('./icons/shop/Ibaco_logo.jpg'),
  list_active: require('./icons/shop/list_act.png'),
  list_inactive: require('./icons/shop/list-inact.png'),
  grid_active: require('./icons/shop/grid_act.png'),
  grid_inactive: require('./icons/shop/grid_inact.png'),
  up_arrow: require('./icons/shop/up_arrow.png'),
  shop_product_dropdown: require('./icons/shop/shop_product_dropdown.png'),
  locate_me_icon: require('./icons/shop/locate_me.png'),
  shop_bottom_tab_active_new: require('./icons/shop/shop_bottom_tab_active_new.png'),
  shop_bottom_tab_inactive: require('./icons/shop/shop_bottom_tab_inactive.png'),
  arrow_down: require('./icons/shop/arrow_down.png'),
  carousel: require('./icons/shop/carousel.png'),
  underline:require('./icons/shop/underline.png'),

  // Login
  google_icon: require('./icons/login/google_icon.png'),
  login_bac: require('./icons/login/loginbac.png'),
  login_background: require('./icons/login/login_background.png'),
  login_bottom_tab_arrow: require('./icons/login/login_bottom_tab_arrow.png'),

  // singel product
  zoom_image_icon: require('./icons/product/zoom_image_icon.png'),
  gross_weight_down_arrow: require('./icons/product/gross_weight_down_arrow.png'),
  red_arrow_icon: require('./icons/product/red_arrow_icon.png'),

  //checkout
  checkout_home: require('./icons/checkout/checkout_home.png'),
  checkout_others: require('./icons/checkout/checkout_others.png'),
  checkout_work: require('./icons/checkout/checkout_work.png'),
};

export default ImageAssets;
